### PR TITLE
handle well column

### PR DESCRIPTION
**Pull request by jburel**
This PR fixes the issue noticed when working on notebook for workshop

cc @dominikl

### CODE REVIEW

**Comment by dominikl** [comment]
Looks good, thanks @jburel . Good to merge from my point of view.

**Comment by dominikl** [comment]
I think this is good to merge. Could handle `Float` issue in a separate PR?

**Comment by jburel** [comment]
Tests are green see https://github.com/ome/openmicroscopy/pull/6280
* Mask is not supported in the tests (failure). To be reviewed in another PR
* Float support to be handled in a follow-up PR

**Comment by jburel** [comment]
Merging since the tests are green and that will allow to move forward with the work started in #56

**Comment by dominikl** [comment]
Thanks @jburel . Btw, there is no `Float` type because there is no `FloatColumn`: https://docs.openmicroscopy.org/omero-blitz/5.5.8/javadoc/omero/grid/Column.html .

**Comment by jburel** [comment]
@dominikl Thanks for pointing that out. This seems like a missing part in the spec

**Pull request merged**
