### PR TITLE
Bugfixes and improvements - 2

### PR DESCRIPTION
**Pull request by dominikl**
- Fix an issue with `DataManagerFacility.createDataset()`
- Add new method `DataManagerFacility.changeGroup()`

The issue with createDataset was: If you create a dataset and add it to a project within the same call and then do the same again with another dataset but without reloading the project in between, then the first dataset gets unlinked from the project again. 

Integration tests: https://github.com/openmicroscopy/openmicroscopy/pull/6048

### CODE REVIEW

**Comment by rgozim** [comment]
It took a while to get the integration tests running on my system, but yea, everything seems to work fine.

**Comment by dominikl** [comment]
Maybe we just scrap the integration tests... they're definitely a big pain now to run with the separated repositories!

**Comment by rgozim** [comment]
Try this out when you get a chance - https://github.com/openmicroscopy/openmicroscopy/pull/6060

Makes running and using the integration tests much easier.

Procedure I did, was:
- checked out your branch (this one)
- ran `gradle publishToMavenLocal`
- changed omero.properties `versions.omero-gateway` in openmicroscoy project to be `5.5.3-SNAPSHOT
- ran `build.py build`
- imported OmeroJava as a gradle project in intellj
- started local omero server
- ran your tests :)

**Comment by joshmoore** [comment]
> Maybe we just scrap the integration tests...

😱 🙉 

We will soon face the same issue with the python integration tests. Probably worth some thought into what will make this easier.

**Comment by joshmoore** [comment]
Merging for 5.5.3. Plan is to get integration tests green before releasing.

**Pull request merged**
