### PR TITLE
Check for pixel size unit == pixel

### PR DESCRIPTION
**Pull request by dominikl**
This should fix https://github.com/ome/omero-insight/issues/102 .

/cc @joshmoore @jburel

### CODE REVIEW

**Comment by dominikl** [comment]
Now catch the exception instead of checking for pixel size unit. Unfortunately can't log the exception as there's no reference to the gateway.

**Comment by joshmoore** [comment]
Thanks, @dominikl. Happy for someone to test this as is. I'll work separately on the tests and on updating https://github.com/ome/omero-blitz/pull/76 as discussed.

**Comment by joshmoore** [comment]
Added a unit test (that's hopefully passing both with and without ome/omero-blitz#76)

**Comment by joshmoore** [comment]
"everything works now" from @jburel. Merging and bumping the version.

**Pull request merged**
