### PR TITLE
Migrate unit test from openmicroscopy

### PR DESCRIPTION
**Pull request by jburel**
* Migrate unit test from openmicroscopy
 * Display the output of the test in the console
 * Run ``cleanTest`` before every run

Make sure travis is green
cc @dominikl

### CODE REVIEW

**Comment by dominikl** [comment]
Thanks. Don't know why they were left behind in the openmicroscopy repo...
But I'm not sure if travis really ran the`PolylineAndPolygonTest` tests, can't see them in the output.

**Comment by jburel** [comment]
you are correct the tests do not seem to be run

**Comment by jburel** [comment]
@dominikl it should be fixed now
```
model.unit > model.unit.active > omero.gateway.model.PolylineAndPolygonTest.testSetPointsForPolygon PASSED

model.unit > model.unit.active > omero.gateway.model.PolylineAndPolygonTest.testSetPointsForPolyline PASSED
```

**Comment by dominikl** [comment]
Thanks @jburel ! Good to merge 👍

**Pull request merged**
